"""empty message

Revision ID: 1ba77fe0b1b7
Revises: 6a7afd382835
Create Date: 2019-03-06 22:58:16.322346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba77fe0b1b7'
down_revision = '6a7afd382835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tracking_number', table_name='orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tracking_number', 'orders', ['tracking_number'], unique=True)
    # ### end Alembic commands ###
