"""empty message

Revision ID: 8dc4ab894e31
Revises: 1ba77fe0b1b7
Create Date: 2019-03-07 16:21:21.538388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc4ab894e31'
down_revision = '1ba77fe0b1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('import_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'import_date')
    # ### end Alembic commands ###
